// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aipfyweadruyfgzftxig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpcGZ5d2VhZHJ1eWZnemZ0eGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTcwNDgsImV4cCI6MjA2MTE5MzA0OH0.UMxUEYkeIhsESTGeQ9HkSvdcXMNTt0hJNv5OI4WTHzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);